/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.yydigital.realswitch;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;


// This proxy can be created by calling Realswitch.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=RealswitchModule.class,
propertyAccessors = {
	TiC.PROPERTY_VALUE,
	TiC.PROPERTY_TITLE_ON,
	TiC.PROPERTY_TITLE_OFF,
	TiC.PROPERTY_COLOR,
	TiC.PROPERTY_FONT,
	TiC.PROPERTY_TEXT_ALIGN,
	TiC.PROPERTY_VERTICAL_ALIGN
}
)
public class RealSwitchProxy extends TiViewProxy
{


	

	// Constructor
	public RealSwitchProxy()
	{
		super();
		setProperty(TiC.PROPERTY_VALUE, false);
		
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		return new RealSwitch(this);
	}

}